### ISSUE TITLE
new openplay

### ISSUE THREAD

**Issue by blackghostaddon** [jsergio123/script.module.resolveurl#237] opened 2019-11-25 15:29 UTC
can u add, please 
hxxps://player.openplay.vip/player.php?id=%s
hxxps://player.openplay.vip/player.php?id=NjE0Mg

**Comment by Gujal00** [comment] 2019-11-26 07:13
Resolving this is easily done by the GenericResolver, however this sneaky "hoster" is basically storing the video chunks disguised as PNG files in googledocs. FFMPEG based players such as Kodi/VLC can't play it as it sees the PNG tag in the binary and will fail at playing
```
�PNG

```
Read about it here
`https://forum.kodi.tv/showthread.php?tid=349359`

**Closed as completed** 2019-11-26 18:40 UTC

**Comment by L2501** [comment] 2019-11-30 08:05
you can play it using inputstream.adaptive and a small patch 
https://github.com/L2501/inputstream.adaptive/commit/659fccef260d9f7b147566170aea97d5c74bd6fc

**Comment by Gujal00** [comment] 2019-12-03 08:52
@L2501 the issue is the extensions are known such as .txt or .png and the binary header inside the file also matches .png so unless Inputstream adaptive can ignore the binary header and treat it as MP4 it cant play. Can you check if it can play, if so it is a good option to play these fake hoster m3u8
