### ISSUE TITLE
GDrive integration doesn't seem to be working

### ISSUE THREAD

**Issue by caperucitaferoz** [jsergio123/script.module.resolveurl#357] opened 2020-08-04 10:55 UTC
The following error occurs:
ERROR: ResolveURL: IndexError Error - From: googlevideo Link: https: //drive.google.com/file/d / .....: no such group

A possible solution would be to remove number 1 from ... doc_id.group (1) on this line:
https://github.com/jsergio123/script.module.resolveurl/blob/f432f8e7dccc34db7e9a51dc08394b49a77ad176/lib/resolveurl/plugins/googlevideo.py#L62

What would be finally:
video = 'plugin://plugin.video.gdrive/?mode=video&amp;instance=gdrive1&amp;filename=%s&amp;content_type=video' % doc_id.group()

**Comment by caperucitaferoz** [comment] 2020-08-05 04:59
I am wondering if it would be possible to use [plugin.googledrive](https://github.com/cguZZman/plugin.googledrive) instead of GDrive ...

**Comment by Gujal00** [comment] 2020-08-09 02:48
@caperucitaferoz Do you have any gdrive video link that I can test with?

**Comment by caperucitaferoz** [comment] 2020-08-09 08:23
https://drive.google.com/file/d/1YSvtdjgcFenTniqf3P1jxU5jt0WAY8K0/view?usp=sharing

**Comment by Gujal00** [comment] 2020-08-09 08:53
That link resolves correctly and plays fine with SMR Link tester even without gdrive or googledrive addons
`2020-08-09 20:50:43.466 T:6420  NOTICE: SMR Link Tester: Link Resolved: |https://drive.google.com/file/d/1YSvtdjgcFenTniqf3P1jxU5jt0WAY8K0/view?usp=sharing|https://r1---sn-ntqe6nel.c.drive.google.com/videoplayback?expire=1596977433&ei=2bgvX6iOJtLjiwSvmIjwAQ&ip=222.154.48.244&cp=QVNOWEpfVlRRRFhOOnV4ZzFPak9RMHpJY3pTeWFrWHAtbW1HdkNDRkhWb1NBTTZmNnRFUHFkVEI&id=48e8c10bc60f0f19&itag=37&source=webdrive&requiressl=yes&mh=Di&mm=32&mn=sn-ntqe6nel&ms=su&mv=m&mvi=1&pl=21&sc=yes&ttl=transient&susc=dr&driveid=1YSvtdjgcFenTniqf3P1jxU5jt0WAY8K0&app=texmex&mime=video/mp4&vprv=1&prv=1&dur=35.665&lmt=1596559534836086&mt=1596962894&sparams=expire,ei,ip,cp,id,itag,source,requiressl,ttl,susc,driveid,app,mime,vprv,prv,dur,lmt&sig=AOq0QJ8wRQIgUdw2VViXVEzAdo0KEnTzEOY2_KMj83kq7CKsA7KP2mICIQCmKRLGArqtsdp5EX52ZpgYxFogcldfxutGhwMliobzdA==&lsparams=mh,mm,mn,ms,mv,mvi,pl,sc&lsig=AG3C_xAwRQIgU4e1dfnMQkOgdXqeRnDGd_BeZB3cNpLgd318DxrxvGgCIQDQRahJRdhqKwBxvmHlT8DceWxDExaM4n7F-UWeybbQCQ==|Cookie=NID%3D204%3DlWLKFg2-dd9ji3DIRDVOS_h986r8a21xT5KR1FlyjGGrKtfdGcgtFZW980eUEOlCKKak5LsJo28D9Lo9CFu3OP3UKbnk3CHI3wVBsme6uwcd2afE5XRc0T0Xe43PPrfL5lw5p7VBX66Q9w38q-4l1a8io32JAf_x-xdbQd-0XlY%3B+expires%3DMon%2C+08-Feb-2021+08%3A50%3A33+GMT%3B+path%3D%2F%3B+domain%3D.google.com%3B+HttpOnly%2C+DRIVE_STREAM%3DQ2-XDnHXGnU%3B+Domain%3D.drive.google.com%3B+Path%3D%2F%3B+Secure%3B+HttpOnly%3B+SameSite%3Dnone&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A77.0%29+Gecko%2F20100101+Firefox%2F77.0| (ENCODED)`

**Comment by caperucitaferoz** [comment] 2020-08-09 09:34
Can you contact me privately at caperucitaferoz@protonmail.com?

**Comment by caperucitaferoz** [comment] 2020-08-10 07:09
I think I have found another error in this option.
Although in the settings we do not have the option "Use external GDrive ..." checked whenever this addon is installed it will try to use it to solve it.
I think this is because of the line:https://github.com/jsergio123/script.module.resolveurl/blob/f432f8e7dccc34db7e9a51dc08394b49a77ad176/lib/resolveurl/plugins/googlevideo.py#L58

... that should be:
if xbmc.getCondVisibility('System.HasAddon(plugin.video.gdrive)') and self.get_setting('GoogleResolver_use_gdrive'):

**Comment by Gujal00** [comment] 2020-10-30 07:34
plugin.video.gdrive seems to be abandoned and removed from kodi repo. For now no solution. may have to be rewritten using plugin.googledrive when that plugin starts working, currently that is also broken
This is Google protecting their assets from being accessed by non gapps, so this plugin may have to be abandoned

**Comment by Gujal00** [comment] 2020-11-06 01:33
@caperucitaferoz I have modified the plugin to use googledrive addon in https://github.com/jsergio123/script.module.resolveurl/commit/59b67abbbb1e9774480790c6ee08d2ed22b4de5e
Can you test and report back please. 
I have tested with
plugin.googledrive v1.4.8
script.module.clouddrive.common v1.3.7
PS: _GoogleDrive addon is available for Kodi up to Leia, so cant use it on Matrix_

**Comment by Gujal00** [comment] 2020-11-06 22:46
@caperucitaferoz v5.1.13 released with the fix, test and report please

**Comment by kodi-rc** [comment] 2020-11-18 13:31
@Gujal00 

Kodi 18.9 , Linux Mint x64 X11 Cinnamon
script.module.resolveurl version="5.1.14"  - 2020/11/18

I tested this link below:
https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview

using plugin.googledrive 1.4.10 and clouddrive.common 1.3.9
https://mirrors.kodi.tv/addons/leia/plugin.googledrive/
https://mirrors.kodi.tv/addons/leia/script.module.clouddrive.common/

https://github.com/cguZZman/plugin.googledrive

and returned the error:
**ResolverError: Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.**

see the full error log:

```
ERROR: ResolveURL: ResolverError Error - From: googlevideo Link: https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview: Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
2020-11-18 10:13:09.384 T:140009776584448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resolveurl.resolver.ResolverError'>
                                            Error Contents: Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
                                            Traceback (most recent call last):
                                              File "/home/ultimate/.kodi/addons/plugin.video.vfohd/addon.py", line 1692, in <module>
                                                listar_servidores(url, name, iconimage)
                                              File "/home/ultimate/.kodi/addons/plugin.video.vfohd/addon.py", line 614, in listar_servidores
                                                player(ret[1], name, iconimage)
                                              File "/home/ultimate/.kodi/addons/plugin.video.vfohd/addon.py", line 576, in player
                                                stream_url = hmf.resolve()
                                              File "/home/ultimate/.kodi/addons/script.module.resolveurl/lib/resolveurl/hmf.py", line 187, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "/home/ultimate/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/googlevideo.py", line 78, in get_media_url
                                                response, video_urls = self._parse_google(web_url)
                                              File "/home/ultimate/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/googlevideo.py", line 145, in _parse_google
                                                sources = self._parse_gdocs(response.content)
                                              File "/home/ultimate/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/googlevideo.py", line 220, in _parse_gdocs
                                                raise ResolverError(reason)
                                            ResolverError: Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
                                            -->End of Python script error report<--
```
-------------------
my Addon Code Sample:

```
def msg(text):
	dialog = xbmcgui.Dialog()
	ok = dialog.ok('myAddon', text)


def player(url, name, iconimage):
	hmf = resolveurl.HostedMediaFile(url.encode('utf-8'))
	if not hmf:
		msg('Not supported')
	else:
		stream_url = hmf.resolve()
		try:
			listitem = xbmcgui.ListItem(name, iconImage='DefaultVideo.png', thumbnailImage=iconimage)
			listitem.setPath(stream_url)
			listitem.setInfo( type="Video", infoLabels={ "Title": name } )
			listitem.setProperty('mimetype', 'video/mp4')
			listitem.setProperty('IsPlayable', 'true')

			xbmcPlayer = xbmc.Player()
			xbmcPlayer.play(item=stream_url, listitem=listitem)

		except:
			msg('There was an error opening the file:\n' + url.encode('utf-8'))
```

**Comment by Gujal00** [comment] 2020-11-18 20:06
@kodi-rc 
That error is coming from line 78 which means it is not using the googledrive addon.
Two things are required.
1. Googledrive addon installed (which you have done) and then authenticate inside that addon with your google account. SMR uses the OAUTH token generated for your google account by the Googledrive addon.
2. In SMR Settings, enable usage of googledrive addon
![SMR Settings](https://i.imgur.com/EjfvjnM.png)

if things are setup correctly, and when you call hmf.resolve() you should see a brief notification on top right corner as below
![SMR](https://i.imgur.com/SzNnCvA.png)
Beyond that the playback is by google drive addon

**Comment by kodi-rc** [comment] 2020-11-19 01:01
@Gujal00 Thanks for the answer!

I did what you asked for, and now it **worked with another link that was not saturated with requests.**

But in this link that I indicated first:
https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview

If I try to access it through the browser and click on the play button. displays the error message:

> This video cannot be played at this time. The number of reproductions allowed has been exceeded. Try again later.

If I try to execute this link through the SMR Link Tester it does not load the video and shows this error log:
```
2020-11-18 21:47:45.155 T:139879128434432  NOTICE: SMR Link Tester: Version: |1.1.3| Queries: |{'mode': 'main'}|
2020-11-18 21:47:45.155 T:139879128434432  NOTICE: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '1', '', 'resume:false']|
2020-11-18 21:47:45.187 T:139880097113856  NOTICE: [plugin.googledrive][service-download-139880097113856]: Service 'download' started in port 33477
2020-11-18 21:47:45.191 T:139879111649024  NOTICE: [plugin.googledrive][service-export-139879111649024]: Service 'export' started.
2020-11-18 21:47:45.192 T:139880080328448  NOTICE: [plugin.googledrive][service-source-139880080328448]: Service 'source' started in port 8587
2020-11-18 21:47:45.192 T:139879023372032  NOTICE: [script.module.clouddrive.common][service-source-139879023372032]: Service 'source' started in port 8585
2020-11-18 21:47:45.192 T:139879013406464  NOTICE: [plugin.googledrive][service-player-139879013406464]: Service 'player' started.
2020-11-18 21:47:50.280 T:139880348763904 WARNING: CAddonSettings[plugin.video.youtube]: failed to load value "" for setting kodion.access_token.expires
2020-11-18 21:47:50.328 T:139880348763904  NOTICE: SMR Link Tester: Version: |1.1.3| Queries: |{'link': 'https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview', 'mode': 'play_link'}|
2020-11-18 21:47:50.328 T:139880348763904  NOTICE: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '2', '?link=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys%2Fpreview&mode=play_link', 'resume:false']|
2020-11-18 21:47:50.328 T:139880348763904  NOTICE: SMR Link Tester: Playing Link: |https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview|
2020-11-18 21:47:50.362 T:139880348763904  NOTICE: SMR Link Tester: Link Supported: |https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview|
2020-11-18 21:47:50.371 T:139880348763904  NOTICE: SMR Link Tester: Link Resolved: |https://drive.google.com/file/d/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/preview|plugin://plugin.googledrive/?action=play&content_type=video&driveid=**************************&item_id=1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys|
2020-11-18 21:47:51.875 T:139881919167168  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.smr_link_tester/?link=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys%2Fpreview&mode=play_link
2020-11-18 21:47:51.948 T:139879136827136 WARNING: CPythonInvoker(16, /home/ultimate/.kodi/addons/plugin.googledrive/addon.py): the python script "/home/ultimate/.kodi/addons/plugin.googledrive/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon4xbmc7MonitorE
2020-11-18 21:47:52.880 T:139881919167168   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://www.googleapis.com/drive/v3/files/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys?alt=media|Authorization=B***bla bla bla*****************
2020-11-18 21:47:52.881 T:139879136827136  NOTICE: Creating InputStream
2020-11-18 21:47:53.401 T:139879136827136   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-11-18 21:47:53.401 T:139879136827136   ERROR: CCurlFile::Open failed with code 403 for https://www.googleapis.com/drive/v3/files/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys?alt=media:
2020-11-18 21:47:53.856 T:139879136827136   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2020-11-18 21:47:53.856 T:139879136827136   ERROR: CCurlFile::Open failed with code 403 for https://www.googleapis.com/drive/v3/files/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys?alt=media:
2020-11-18 21:47:53.856 T:139879136827136   ERROR: Open - failed to open source <https://www.googleapis.com/drive/v3/files/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys?alt=media|Authorization=B***bla bla bla*****************>
2020-11-18 21:47:53.856 T:139879136827136   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.smr_link_tester/?link=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys%2Fpreview&mode=play_link]
2020-11-18 21:47:53.856 T:139879136827136  NOTICE: CVideoPlayer::OnExit()
2020-11-18 21:47:53.874 T:139881919167168  NOTICE: CVideoPlayer::CloseFile()
2020-11-18 21:47:53.881 T:139881919167168  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-18 21:47:53.881 T:139881919167168  NOTICE: VideoPlayer: finished waiting
```
------
But this same file if I try to access the browser with this link from an custom player, using the googlevideo code:
https://opensv.biz/gd/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/

This player can play the video even on the official google page say that the video has exceeded the number of reproductions

***************************
**Would it be possible to run the video on the kodi as it is on this custom player?
https://opensv.biz/gd/1FlSAAwZFPQ9EaAHGKaK2txhE5JTXe7Ys/**


note: another link with excessive requests
https://drive.google.com/file/d/1lg9Yn9D9av-ZTyh-oMk_qemGgczYvlDi/edit

**Comment by Gujal00** [comment] 2020-11-19 01:15
@kodi-rc 
From what I can see these gdrive files are not public. You can see error 403 when googledrive addon is trying to access it.
From looking at the code, it seems like they use their own oauth token hidden behind php for the private files. I dont see a way to play these from googledrive addon or from SMR

**Closed as completed** 2020-11-21 04:47 UTC
Labels: good first issue
