### ISSUE TITLE
NETU

### ISSUE THREAD

**Issue by blackghostaddon** [jsergio123/script.module.resolveurl#322] opened 2020-04-03 15:34 UTC
any  help to update  netu server
hxxps://netu.tv/watch_video.php?v=vH9I5z8HsGE6
and powvideo.

**Comment by L2501** [comment] 2020-04-03 17:19
duplicate of https://github.com/jsergio123/script.module.resolveurl/issues/320
it also uses recaptcha so you will need to use a browser anyway.

**Comment by Gujal00** [comment] 2020-04-03 22:48
netu, hqq and waaw are all the same site and they all are enforcing Google Recaptcha
No solution for now

**Closed as completed** 2020-11-06 06:24 UTC
Labels: duplicate, Broken
